Daily Reminder
Lowie-s-Leetcode-Community/LCHelper pull request #53
Opened 2024-08-30 09:43 UTC by HaruKatou

2024-09-04 10:18 UTC, cdf144 requested changes

2024-09-04 10:20 UTC, cdf144 approved these changes

2024-09-04 10:28 UTC, lowie1803 commented on .gitignore
> +resrc/weekly.txt
`resrc/**`

2024-09-04 10:28 UTC, lowie1803 commented on cogs/automation/intervally/daily_auto.py
> +    datetime.time(hour=8, minute=30, tzinfo=datetime.timezone.utc): "Hi {mention}, it's your turn to write the editorial today! Please complete it by 6pm to help other community members in need! <:bl
Use `Asset` library property for this

2024-09-04 10:28 UTC, lowie1803 commented on cogs/automation/intervally/daily_auto.py
> +            score_value = 8
Use a dictionary for this:
```py
EDITORIAL_SCORES = {
  "Easy": 8,
  "Medium": ...
}
```

2024-09-04 10:28 UTC, lowie1803 commented on cogs/automation/intervally/daily_auto.py
> +        if score_value <= 0:
These copy-pasted lines are very unrelevant :(

2024-09-05 11:52 UTC, lowie1803 approved these changes

2024-09-05 11:52 UTC, lowie1803 commented on cogs/automation/intervally/daily_auto.py
> +        for reminder_time in REMINDER_MESSAGES.keys():
Đoạn code này chưa sạch và tối ưu đâu nhé. Vì tần suất lặp lại của task này rất lớn (1p/1 lần), nên ta cần có logic để return luôn nếu reminder time không nằm trong map này.

Typically mình sẽ tạo một object datetime chỉ sử dụng `hour` và `minute` của now và sử dụng `not in` để `return` khỏi hàm, trc khi thực hiện các tác vụ tiếp theo.

2024-09-05 11:53 UTC, lowie1803 requested changes

2024-09-05 11:53 UTC, lowie1803 commented on cogs/automation/intervally/daily_auto.py
> +    async def reminder_task(self):
Đoạn code này chưa sạch và tối ưu đâu nhé. Vì tần suất lặp lại của task này rất lớn (1p/1 lần), nên ta cần có logic để return luôn nếu reminder time không nằm trong map này.

Typically mình sẽ tạo một object datetime chỉ sử dụng hour và minute của now và sử dụng not in để return khỏi hàm, trc khi thực hiện các tác vụ tiếp theo.

2024-09-06 15:14 UTC, lowie1803 approved these changes

2024-09-06 15:38 UTC, merged